### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by eNeRGy164**
Same small fixes

### CODE REVIEW

**Comment by eNeRGy164** [comment]
@dennisdoomen disappointed in the handling times on this repo 😉

**Comment by dennisdoomen** [comment]
The what?

**Comment by eNeRGy164** [comment]
I'm just joking, on continousimprover.com the PR was merged in 15 minutes, here the PR has not been handled in 23 hours.

**Comment by dennisdoomen** [comment]
I just noticed I was not watching the repo yet ;-)

**Comment by eNeRGy164** [comment]
As the watch number was 0, I was expecting that was the case. That's why I @'ed you :)

**Comment by dennisdoomen** [comment]
It's a shame the Github diff viewer is completely useless here, but I trust you blindly.

**Comment by eNeRGy164** [comment]
Thanks for the trust, the changes look correctly @ https://liquidprojections.net/getting-started/

**Pull request merged**
